// <auto-generated />
namespace Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Add_requied_constraint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_requied_constraint));
        
        string IMigrationMetadata.Id
        {
            get { return "202003200734077_Add_requied_constraint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
